server:
  service:
    type: ClusterIP

alertmanager:
  enabled: true

pushgateway:
  enabled: false

serverFiles:
  alerting_rules.yml:
    groups:
      - name: cpu-alerts
        rules:
          - alert: HighCPUUsage
            expr: (1 - avg(rate(node_cpu_seconds_total{mode="idle"}[2m]))) > 0.8
            for: 2m
            labels:
              severity: warning
            annotations:
              summary: "High CPU usage detected"
              description: "CPU usage is above 80% for more than 2 minutes."