{
 "title": "Cluster Overview dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Targets up",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Targets by job",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 16, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count by (job) (up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Targets Down",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(up) - sum(up)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 16, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum by (pod, container) (\n  rate(container_cpu_usage_seconds_total{container!=\"\"}[5m])\n)",
     "legendFormat": "{{container}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage (%)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}