apiVersion: v1
kind: Service
metadata:
  name: sample-app
  namespace: observability
  labels:
    app: sample-app
spec:
  selector:
    app: sample-app
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP